enable developer mode for p11ne-db tool
TBA

Signed-off-by: EC2 Default User <ec2-user@ip-172-31-3-52.us-west-2.compute.internal>

diff --git a/tools/p11ne-db b/tools/p11ne-db
--- a/tools/p11ne-db
+++ b/tools/p11ne-db
@@ -1,8 +1,8 @@
-#!/usr/bin/env bash
-# Copyright 2020-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
+#!/bin/bash
+# Copyright 2020-2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: Apache-2.0
 
-MY_VERSION="1.1"
+MY_VERSION="1.2"
 MY_NAME="p11ne-db"
 MY_DESC="p11ne database formatting tool"
 
@@ -21,17 +21,14 @@ Commands:
     --out-file      <output file>
     --kms-key-id    <id of the KMS CMK key used to encrypt the private key>
     --kms-region    <region of the KMS CMK key>
-
+    --dev-mode      <developer mode>
 "
 
 # Database format converter
 cmd_pack-key() {
 
     local nargs="$#";
-
-    if [ $nargs -ne 12 -a $nargs -ne 14 ]; then
-        die "Invalid arguments. Please use \`$0 help\` for help."
-    fi
+    local dev_mode=false
 
     while [[ "$#" -gt 0 ]]; do
         case $1 in
@@ -40,15 +37,17 @@ cmd_pack-key() {
             --key-file) key_file="$2"; shift ;;
             --cert-file) cert_file="$2"; shift ;;
             --out-file) out_file="$2"; shift ;;
-            --kms-key-id) key_id="$2"; shift ;;
-            --kms-region) region="$2"; shift ;;
+            --kms-key-id) kms_key_id="$2"; shift ;;
+            --kms-region) kms_region="$2"; shift ;;
+	        --dev-mode) dev_mode=true; shift ;;
             *) cmd_help; die "Invalid argument: $1. Please use \`$0 help\` for help.";;
         esac
         shift
     done
 
-    if [ $nargs -eq 12 -a -n "$cert_file" ]; then
-        die "Invalid arguments. Please use \`$0 help\` for help."
+    required_arg_vars "id,label,key_file,out_file"
+    if [ $dev_mode != "true" ]; then
+        required_arg_vars "kms_key_id,kms_region"
     fi
 
     # The key file
@@ -61,19 +60,48 @@ cmd_pack-key() {
     key=$(<"$key_file")
     ok_or_die "Cannot open the input file."
 
-    #ensure aws cli
-    which aws > /dev/null
-    ok_or_die "aws cli is not present on this machine. Please install the aws cli and try again."
-
-    #encrypt with kms - the result is the Base64 representation of the cyphertext
-    enc_key=$(aws kms encrypt --key-id $key_id --plaintext "$key" --region $region --query CiphertextBlob --output text)
-    ok_or_die "Failed to encrypt the key"
-
     # Read the cert (optional)
     local cert
     if [ -n "$cert_file" -a -f "$cert_file" ]; then
         cert=$(<"$cert_file")
     fi
+
+    if [ "$dev_mode" != "true" ]; then
+        out_data=$(build_keystore_data "$id" "$label" "$key" "$cert" "$kms_key_id" "$kms_region")
+    else
+        out_data=$(build_keystore_data_with_plain_key "$id" "$label" "$key" "$cert")
+    fi
+
+    echo "$out_data" > "$out_file.db"
+    ok_or_die "Cannot write to output file."
+}
+
+# Verify required arguments
+#
+required_arg_vars() {
+    # Tokenize the comma-separated argument
+    IFS=',' read -ra var_array <<< "$1"
+
+    for var_name in "${var_array[@]}"; do
+        [ -n "${!var_name+defined}" ] || die "--${var_name//_/-} argument is required. Please use \`$0 help\` for help."
+    done
+}
+
+build_keystore_data() {
+    local id=$1
+    local label=$2
+    local cert=$3
+    local key=$4
+    local kms_key_id=$5
+    local kms_region=$6
+
+    #ensure aws cli
+    which aws > /dev/null
+    ok_or_die "aws cli is not present on this machine. Please install the aws cli and try again."
+
+    #encrypt with kms - the result is the Base64 representation of the cyphertext
+    enc_key=$(aws kms encrypt --key-id $kms_key_id --plaintext "$key" --region $kms_region --query CiphertextBlob --output text)
+    ok_or_die "Failed to encrypt the key"
 
     local out_data
     out_data=$( jq -Rn \
@@ -83,9 +111,24 @@ cmd_pack-key() {
             --arg d "$cert" \
 	     '[{encrypted_pem_b64: $a, id: $b | tonumber, label: $c, cert_pem: $d}] | del(.[][] | select(. == ""))')
     ok_or_die "Cannot format the input key."
+    echo "$out_data"
+}
 
-    echo "$out_data" > "$out_file.db"
-    ok_or_die "Cannot write to output file."
+build_keystore_data_with_plain_key() {
+    local id=$1
+    local label=$2
+    local cert=$3
+    local key=$4
+
+    local out_data
+    out_data=$( jq -Rn \
+            --arg a "$key" \
+            --arg b "$id" \
+            --arg c "$label" \
+            --arg d "$cert" \
+	     '[{plain_pem_b64: $a, id: $b | tonumber, label: $c, cert_pem: $d}] | del(.[][] | select(. == ""))')
+    ok_or_die "Cannot format the input key."
+    echo "$out_data"
 }
 
 # Exit with an error message and (optional) code
